services:
  - type: web
    name: fastapi-app
    runtime: python3.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app -b 0.0.0.0:$PORT -k uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
